### ISSUE TITLE
How to make url routing

### ISSUE THREAD

**Issue by rk-fsdev** [dbalas/landingplate#60]
What if I add some menu links on the top and it will go to other pages, you made good partials, it is fine, but I want to update body with some links

**Comment by dbalas** [comment]
Hello @rk-fsdev, thanks for your comment.
This boilerplate is only for simple one-page landing pages so it only have an index.html. If you want more pages you will need to update webpack.config.js but I recommend you a static page generator like gatsby, next, nuxt, etc
